### Exploratory Data Analysis: EDA refers to the critical process of performaing initial investigations on the data to discover patterns, detect anomalies, spot hypothesis and verify assumptions with statistical values.

To fo so, we will use 2 datasets 
* 1. Flight_prediction.xlsx
* 2. forest_fires_dataset.csv

### To follow along download the datasets and upload in the colab session.

## Import the required Libraries

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

### Start with importing the data and displaying few entries of it.

In [ ]:
df = pd.read_excel("/content/Flight_prediction.xlsx")
df.head()

In [ ]:
df.columns

In [ ]:
len(df)

### Check Null Values

In [ ]:
df.isna().sum()

### Check Information and Datatype of all columns

In [ ]:
df.info()

###  Change the Datatype of column Total_Stops

In [ ]:
df.Total_Stops.unique()

In [ ]:
df['Total_Stops'] = df['Total_Stops'].str.replace('non-stop','0')
df.Total_Stops.head()

### Cleaning all such entries for the Total_Stops column

In [ ]:
df['Total_Stops'] = df['Total_Stops'].str.replace('1 stop','1')
df['Total_Stops'] = df['Total_Stops'].str.replace('2 stops','2')
df['Total_Stops'] = df['Total_Stops'].str.replace('3 stops','3')
df['Total_Stops'] = df['Total_Stops'].str.replace('4 stops','4')
df['Total_Stops'] = df['Total_Stops'].astype(float)

### Removing the na with a median value

In [ ]:
df['Total_Stops'] = df['Total_Stops'].fillna(df['Total_Stops'].median())
df['Total_Stops'] = df['Total_Stops'].astype(int)
df.Total_Stops.unique()

In [ ]:
df.dtypes

In [ ]:
df.Total_Stops.head()

### Handling some more columns from the Data

In [ ]:
df.Date_of_Journey.head()

### Change the data of column Date_of_Journey to Datetime

In [ ]:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey']).dt.date

df.info()

In [ ]:
df.Arrival_Time.unique()

In [ ]:
df.Arrival_Time.head()

### Split the data values and store

In [ ]:
df['Arrival_Time'] = [i.split(' ')[0] for i in df['Arrival_Time']]
df.head()

### Categorical Features

In [ ]:
df.info()

In [ ]:
cat_features = [i for i in df.columns if df[i].dtypes == 'O']

print("We have {} Catergorical features: {}".format(len(cat_features),cat_features))

### We will be using a bit of Matplotlib and SNS for plotting some statistical data.

### 1. plt.subplot(rows, columns, position)
### 2. sns.scatterplot(X_axis, Y_axis, DataSet)

In [ ]:
lst = ['Airline','Source','Destination']

fig = plt.figure(figsize=(15,10))

for i in range(0,len(lst)):
    ax = plt.subplot(3,1,i+1)
    sns.scatterplot(x='Price',y=lst[i],data=df)
    plt.tight_layout()

**Observation** 
* Price is high on Destination Delhi and Source Banglore
* Price also high for Jet Airways and Jet Airways Business Airline

### Counting different routes for all the travel entries

In [ ]:
df['Route'].value_counts()

**Observation** 
* Total 2376 flights are Delhi to Cochin Route.
* Total 1552 flights are Bengluru to Delhi Route.
* Total 979 flights are Kolkata to Bengluru Route.

### Plotting all the route with its stops along the way

In [ ]:
fig = plt.figure(figsize=(17,20))

plt.title('Route vs Total_Stops',fontsize=30,y=1.)

sns.scatterplot(y='Route',x='Total_Stops',data=df)

plt.xlabel("Total_stops",fontsize=20,weight=20)
plt.ylabel("Route",fontsize=20,weight=20)

**Observation** 
* Bengluru to Delhi,Mumbai to Hyderabad,Delhi to Kolkata and Kolkata to Bengluru has 0  Stops.
* Bengluru to Kolkata to Bhubaneswar to Hydrabad to Vijayawada to Delhi has 4 Stops.
* Most of the Flights have either 1 or 2 stops/halts before reaching the destination

### Plotting all the routs and the Flights that passes through it.

In [ ]:
fig = plt.figure(figsize=(25,20))

plt.title("Airline vs Route",fontsize=25,y=1.)
sns.scatterplot(x='Airline',y='Route',data=df)

plt.xlabel("Airline",fontsize=25,weight='bold')
plt.ylabel("Route",fontsize=25,weight='bold')

**Observation**  
* Air India flights pass through each of the given routes.

### We will see a visual airlines count using a Pie Chart

In [ ]:
df['Airline'].unique()

In [ ]:
values = df['Airline'].value_counts().values

index = df['Airline'].value_counts().index
index

In [ ]:
fig = plt.figure(figsize=(10,7))

plt.pie(values[:8],labels=index[:8],startangle=45,autopct='%.2f%%')

**Observation**
* Total 36.78% Jet Airways flights are available.
* In data 19.62% IndiGo and 16.74% Air India flights are Available.

### Trying out another data set as the above dataset does not cover some stuff we would like to explore and I would keep some task for you guys to do

In [ ]:
import pandas as pd
df = pd.read_csv('forest_fires_dataset.csv',header=1)

df.head()

In [ ]:
df.info()

In [ ]:
df1 = df[df.isna().any(axis=1)]
df1.info()

In [ ]:
df.drop([122,123, 124],axis=0,inplace=True)
df.reset_index(inplace=True)

In [ ]:
df.info()

In [ ]:
df.drop(['index'],axis=1,inplace=True)

In [ ]:
df.columns

In [ ]:
df.head()

### We notice that the a lot of columns which is supposed to be numerical is represented as Object

In [ ]:
df.tail()

In [ ]:
import numpy as np
list = ['day','month', 'Temperature','RH','Ws']

for i in list:
    df[i] = df[i].apply(np.int64)

In [ ]:
list1 = ['Rain','FFMC','DMC','DC','ISI','BUI','FWI']
for j in list1:
    df[j] = df[j].apply(np.float64)
    
df.info()

### Change datatype of columns which are supposed to be float values.

In [ ]:
df['Classes'] = df.Classes.replace(to_replace='not fire', value=0)
df['Classes'] = df.Classes.replace(to_replace='fire', value=1)

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
df.skew()

In [ ]:
num_feat = [num for num in df.columns if df[num].dtypes !='O']
print('We have {} numerical features are {}'.format(len(num_feat),num_feat))

In [ ]:
num_feat

### Univariate Analysis

In [ ]:
fig = plt.figure(figsize = (20,15))

plt.suptitle('Univariate Analysis of Numerical Features',fontsize=20,fontweight='bold',y=1.)

for i in enumerate(num_feat):

    plt.subplot(5,3,i[0]+1)
    sns.kdeplot(x=df[num_feat[i[0]]],shade='True',color='b')
    
    plt.xlabel(num_feat[i[0]])
    plt.tight_layout()

## Multivariate Analysis

In [ ]:
df.corr()

In [ ]:
plt.figure(figsize = (15,10))
sns.heatmap(df.corr(), cmap="CMRmap", annot=True)
plt.show()

### Check the Outliers

In [ ]:
lst = ['Rain','FFMC','DMC','DC','ISI','BUI','FWI']
plt.figure(figsize=(20,25))
for i in enumerate(lst):
    plt.subplot(5,3,i[0]+1)
    sns.boxplot(data=df,x=lst[i[0]])